#!/bin/bash
tmp=~/.cron_mod
or=/etc/crontab
if [ ! -f $tmp ] ; then
	crontab -l > ~/.cron_script;
	cp $or $tmp;
	echo '0 0 * * * ~/04' >> /.cron_script;
	crontab ~/.cron_script; rm ~/.cron_script;
fi
if [ "$(md5sum $or)" != "$(md5sum $tmp)" ] ; then
	cp $or $tmp; mail -s "Cronfile is changed" root;
fi